### ISSUE TITLE
[Repo Request]: MonitorMaestro

### ISSUE THREAD

**Issue by Degra02** [hyprland-community/submissions#5]
### What do you want it to be named?

MonitorMaestro

### What do you want to use it for?

repo link: https://github.com/Degra02/MonitorMaestro
simple tui with json-configurable monitors configurations

**Comment by yavko** [comment]
@Degra02 you've been invited, once you accept all you have to do is use this button to transfer to the org found at the end of the setting page. Also tell me when u transfer, so I can then give you full perms on the repo because github likes to be funny
![image](https://github.com/hyprland-community/submissions/assets/15178513/8328a869-858e-4a35-9b7d-7f14f6a91890)

**Comment by Degra02** [comment]
@yavko Ok, transfered

**Comment by yavko** [comment]
@Degra02 done, I also added the metadata to the description
