### ISSUE TITLE
[Repo Request]: hyprls

### ISSUE THREAD

**Issue by gwennlbh** [hyprland-community/submissions#6]
### What do you want it to be named?

hyprls

### What do you want to use it for?

LSP server for hyprland config files.

See https://github.com/ewen-lbh/hyprls

**Comment by yavko** [comment]
I've sent an invitation for you to join the org, you can transfer the repo using this button found at the bottom of the setting page 
![image](https://github.com/hyprland-community/submissions/assets/15178513/f9ffb4c6-2d2d-4ee3-bafb-717581dfb9f1)
Once you've done it, let me know because GitHub decided transferring ownership doesn't include transferring repo permissions. 🙃

**Comment by gwennlbh** [comment]
Thanks! I transferred the repo :3

**Comment by yavko** [comment]
Okay I've fixed the stuff, I added the maintainer tag too
